# kibana - web instance
#
# Copied from http://cookbook.logstash.net/recipes/using-upstart/

description     "kibana web instance"

start on virtual-filesystems
stop on runlevel [06]
emits kibana-running

# Respawn it if the process exits
respawn
respawn limit 5 30
expect fork

chdir /mnt/kibana/site

script
  su -s /bin/sh -c 'exec "$0" "$@"' kibana -- /usr/bin/ruby /mnt/kibana/site/kibana.rb &
end script

post-start script
  initctl emit kibana-running
end script

